version: '3.8'

services: 
  app:
    build: . 
    command: yarn start
    ports: 
      - "8000:8000"
    links: 
      - db
    volumes: 
      - .:/usr/app
    environment:
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASS: postgres
  db:
    image: postgres:alpine
    container_name: api-db-manadulted
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_DB: manadulted 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    volumes:
      - .:/usr/app